ImageGallery/Models/ErrorViewModel.cs
using System;

namespace ImageGallery.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

ImageGallery/Models/ImageModel.cs
namespace ImageGallery.Models
{
    public class ImageModel
    {
        public int Id { get; set; }
        public string Url { get; set; }
        public string Description { get; set; }

    }
}

ImageGallery/Controllers/HomeController.cs
using ImageGallery.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;

namespace ImageGallery.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

ImageGallery/Controllers/ImageController.cs
using ImageGallery.Service;
using Microsoft.AspNetCore.Mvc;

namespace ImageGallery.Controllers
{
    public class ImageController : Controller
    {


        private readonly ImageService _imageService;

        public ImageController(ImageService imageService)
        {
            _imageService = imageService;
        }


        public IActionResult Index()
        {
            var images=_imageService.GetAllImages();
            return View(images);
        }
    }
}

ImageGallery/Controllers/ImageGalleryController.cs
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Threading.Tasks;

namespace ImageGallery.Controllers
{
    public class ImageGalleryController : Controller
    {
        private readonly string rootPath = Path.Combine(Directory.GetCurrentDirectory(), "wwwroot//uploads");
        public IActionResult Index()
        {
            bool dirExists=Directory.Exists(rootPath);
            if (!dirExists)
            {
                Directory.CreateDirectory(rootPath);
            }
            List<string> imageNames = Directory.GetFiles(rootPath).Select(Path.GetFileName).ToList();
            return View(imageNames);
        }

        [HttpPost]

        public async Task<IActionResult> Index(IFormFile file)
        {
            if (file != null)
            {
                var path = Path.Combine(rootPath, Guid.NewGuid() +
                    Path.GetExtension(file.FileName));
                using(var fs=new FileStream(path, FileMode.Create))
                {
                    await file.CopyToAsync(fs);
                }
                return RedirectToAction("Index");
            }
            return View();  // This is the final code line

        }
    }
}

ImageGallery/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

ImageGallery/Views/Image/Index.cshtml
@model List<ImageModel>

<h2>My view for the images objects display</h2>

<div>
    @foreach( var images in Model)
    {
        <div>
            <img src="@images.Url" alt="@images.Description" />
            <p>@images.Description</p>
        </div>
    }
</div>

ImageGallery/Views/ImageGallery/Index.cshtml
@model List<string>


<div>
    @using (Html.BeginForm("Index","ImageGallery",FormMethod.Post,new{ enctype="multipart/form-data"}))
    {
        <div class="row">
            <div class="form-group col-md-6">
                <input type="file" class="form-control" name="file" />
            </div>
            <div class="form-group col-md-3">
                <input type="submit" class="btn btn-primary" name="submit" value="upload" />
            </div>

        </div>
    }

</div>
<br />
<div>
    <div class="container">
        <div class="card border-primary">
            <div class="card-header font-weight-bold border-primary">
                Image Gallery
            </div>
            <div class="row">
                @if( Model!=null && Model.Any()){
                    @foreach(var imageFile in Model)
                    {
                        <div class="col-md-3" >
                            <div class="alert alert-success">
                                <img src="~/uploads/@imageFile" height="100px" width="200px" />
                            </div>
                            
                        </div>
                    }
                }
                else
                {
                    <div>
                        Images not available
                    </div>
                    
                }

            </div>
        </div>


    </div>
</div>

ImageGallery/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - ImageGallery</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">ImageGallery</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="ImageGallery" asp-action="Index">Image Gallery</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Image" asp-action="Index">My Images Objects</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2024 - ImageGallery - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @RenderSection("Scripts", required: false)
</body>
</html>